### ISSUE TITLE
Blatt 1 Aufgabe 3: Syntax

### ISSUE THREAD

**Issue by paulesn** [FIUS/jvk#25]
Lernziele:

 *  Syntax von den verwendeten Programmkonstrukten erkennen können
 *  Was ist ein Syntaxfehler
 *  Einrückung wann, wie, warum eigentlich ?!

Alle folgenden Teilaufgaben funktionieren nach dem schema: Syntax vorstellen, ein Beispiel geben, dann den vom studenten Beispiele aus dem code von aufgabe 1 suchen lassen

1. a) Aufbau einer `.java` datei/Klasse (nicht im detail, ziel ist nur zu wissen was klasse, was methode und was code ist und wie die schachtelung sein muss; KEINE keywords wie `public` erklären wenn nicht notwendig)
2. b) `...;` eine abgeschlossene Zeile code (ziel fehlende semikolon vermeiden)
3. c) `new Object()`
4. d) `Type var = ...;` var als zwischenspeicher erklären (hält einen finger auf das objekt rechts vom gleichheitszeichen/ wird für wiederverwenden von objekten gebraucht wenn man zwei operationen auf einem objekt ausführen muss)
5. e) `obj.operation()` und `obj.query()` (dzu auch abwandlungen wie `obj.query().operation()` oder `var = obj.query()`)
6. f) Implementierungskommentare
7. g) bewusst verschiedene Syntax Fehler im code erzeugen und die Fehlermeldung von Eclipse beobachten
     *  Semikolon vergessen
     *  Klammerfehler
     *  Tippfehler (z.B. Buchstaben löschen, Groß-/Kleinschreibung verändern)
     *  Punkte durch , ersetzen
     *  `"` durch `'` ersetzen
     *  `new Object()` außerhalb der main Methoder oder der main Klasse

**Comment by TheMrPhantom** [comment]
Im Blatt steht "Darauf folgen die , die den gesamten Inhalt der Klasse umschließen.". Da fehlt eine geschweifte Klammer
