### ISSUE TITLE
Blatt 1 Aufgabe 5: Eine API verwenden / Doku lesen

### ISSUE THREAD

**Issue by paulesn** [FIUS/jvk#27]
Lernziele:

 *  Javadoc zu Methoden und allem anderen in java finden
 *  Alle aufrufbaren methoden eines Objekts herausfinden (z.B. per autocomplete oder per javadoc webseite)
 *  PlayfieldModifier verwenden können
 *  Manche Shapes verwenden können?
 *  Spielfeld-Koordinaten verstehen

Hier müssen Javadoc und Javadoc-Kommentare erklärt werden. Und wie man sie findet!

1. a) den zugehörigen Task und verifier für diese aufgabe ausführen (siehe Aufgabe 4)
2. b) Spawne mehr münzen (mindestens 5, copy paste erlaubt)
     *  Was passiert mit mehreren münzen auf dem gleichen Feld?
     *  Wie funktioniert das Koordinatensystem im Spielfeld?
3. c) Welche anderen Methoden hat der PlayfieldModifier noch? (Beide rausschreiben)
4. d) Platziere 20 münzen auf dem gleichen feld (Dazu die coin-factory als beispiel code angeben)
5. e) Platziere 3 Reihen von 7 Münzen (Dazu line shape und Position als Beispiel code angeben)
6. d) (opt.) Andere shapes / entites nennen und ein spielfeld nachbauen lassen

**Comment by bieniajl** [comment]
Optional Task not yet done, but everything else should be good to Review
